### ISSUE TITLE
Http 404 issue

### ISSUE THREAD

**Issue by MrEnigmamgine** [chisaipete/bestiary#31]
http://chisaipete.github.io/bestiary/tags/<any tag>.html
Trying to sort by tag results in 404 error

**Comment by EpicCyclops** [comment]
I noticed this over the weekend as well. I cloned the project into my own repo and tried building it locally...it looks like the /tags directory is not getting generated under the _site/ directory, and I'm pretty sure it should be. Haven't had time to debug beyond that. And I don't see anything in the commit history that should affect whether the tags plugin runs or not. But I'm new to this and "don't know what I don't know"

**Comment by MrEnigmamgine** [comment]
Yeah I thought it was odd that I didn't see any recent commits, but I'm new
to github so I thought I was just looking in the wrong place.
It's probable that this is a github hosting issue if no changes were made
to the application.

**Comment by EpicCyclops** [comment]
yeah I think something when screwy with the most recent commit on the gh_pages branch?

I've actually managed to fix things on my personal gh-page by wiping out the old gh_pages branch and doing a subtree push of a new gh-pages branch that contains the contents of the "_site" folder, which does actually include the tags directory now (I wasn't seeing it generated on Saturday, probably because I was trying to use Windows).

**Comment by chisaipete** [comment]
It's most likely an issue with Jekyll generation process, it's broken this
way once before. I'm super busy with life right now, but will get to fixing
it ASAP. Is the site completely broken in your eyes?

**Comment by EpicCyclops** [comment]
No it's not completely broken, all the posts are still viewable and you can still do a name search or view by Cr. It's just the links at the top for "undead", "fey", etc lead to 404.

Most likely the tag_gen.rb script is not running when generating the site for github pages

**Comment by AberrationGM** [comment]
Actually, it IS broken. In a way. Your bestiary is the most complete and well-designed list on the net, and a vital tool for my encounter building. On my ongoing campaigns I build a lot of my encounters based on a creature type to uphold story and terrain. It is safe to assume, that a lot of other GMs give a thought about it, too.

But that's ok, i can use another, less-than-complete sources for that.

What really was a blow for me, is that your bestiary was the **only** list that allowed me to make up NPC encounters on the fly. Because you have a lot of Humanoids of different CRs from all of the adventure books, which is really cool and is making up for D&D overall lack of two-legged antiheroes and evildoers (or sudden helpers and mercenaries) in their bestiaries.

**Comment by chisaipete** [comment]
I think I'm only seeing "aberration" as being broken?  This is getting weirder.  Anyone care to look into it further?

**Comment by midgardsormr-bb** [comment]
Hi. Everything seems to be working fine on my side, now. No more 404 errors while clicking on tags.

**Comment by chisaipete** [comment]
Great, I see it fixed now too. Okay, I think I know what happened and how to prevent it in the future, thanks for flagging it and being patient folks!
