### ISSUE TITLE
Explore using webcomponents to look like a stat block

### ISSUE THREAD

**Issue by chisaipete** [chisaipete/bestiary#7]
http://valloric.github.io/statblock5e/

:)

**Comment by thisboyiscrazy** [comment]
I am interested in implementing this, but the issue might be that it requires chrome.

Should be able to use Polymer for poly-fills

**Comment by chisaipete** [comment]
If you want to take a shot at it, go right ahead! I think there are a number of hurdles to making this work with Jekyll, let alone the fact that it's only fully supported in Chrome :smile:  It might be a pipedream, but it is a pretty one.

**Comment by thisboyiscrazy** [comment]
I'm going to work on a "translator" using both repositories first. Then I'll work on integrating it.

**Comment by chisaipete** [comment]
Translator?  Like i18n?

**Comment by thisboyiscrazy** [comment]
I mean a small js file that will read the md files and output a webcomponent.

**Comment by chisaipete** [comment]
Did you get anywhere with this?

**Comment by thisboyiscrazy** [comment]
I have not had time. So not yet.

**Comment by chisaipete** [comment]
I just saw this change in jekyll, this may be fruitful for using the statblock webcomponent!

https://github.com/envygeeks/jekyll-assets/issues/155

**Comment by chisaipete** [comment]
Any new thoughts or movement on this?  Do folks want to see a spicier statblock?

**Comment by farfromunique** [comment]
I do want to see 'spicier' stat blocks! I have both of these projects open right now, because I needed a stat block for a campaign I'm running (character wants a mule, he gets a mule. Who am i to judge?).

If I knew anything about Jekyll, I'd do the work myself, but I only know PHP for server-side stuff (although I'm learning XML/XSL(T) and C#/ASP.NET; I doubt either of those would be helpful).

**Comment by chisaipete** [comment]
Actually, there may be a simpler way to do this, just by updating some css and the output html:

https://codepen.io/retractedhack/pen/gPLpWe

**Comment by farfromunique** [comment]
I started with the HTML that was output for X, and tried to style it from there (meaning we / you could just add a style sheet, instead of having to re-work how the markdown is rendered). I got to this: https://codepen.io/farfromunique/pen/ZxvWmJ/

Things I'm struggling with: 
1. How to semantically define where the section separator marks go. Right now I'm using `:nth-of-type` and counting
2. How to define groups of things (the difference between `top-stat`s and `property-block`s
3. How to differentiate `Actions` from other headers

Some solutions I've come up with, but which may take a lot of manual work: 
1. add in horizontal rules, and style the rule with the SVG styling
2. My gut says the trick may be in sibling combinators (`~` and `+`), but I can't figure out how
3. Actions can be a header level. 

monster name --> H1
medium thing --> H2
property-block --> H3
property-block --> H3
"Actions" --> H4
property-block --> H3
property-block --> H3

This would let us avoid item 2 altogether

Does this make sense, or is there an easier way to manage the conversion?

**Comment by chisaipete** [comment]
Hmm, sorry to be slow on this.  I'm not sure exactly what's going on here, did you just manually update the html output of a single monster from the site and then apply the correct classes and ids to elements and that's what you got?  If so, that's brilliant!  Help me better understand your challenges and perhaps we can get this moving.  Do you have any idea on cross-browser support for this method?

**Comment by Kyrremann** [comment]
I had some spare time on Saturday, and tried to get this working, and managed to do this.
![image](https://user-images.githubusercontent.com/1830501/54511314-e5048200-4950-11e9-84fe-55005d3df451.png)

I made a new layout, where I used values set in the header. Meaning that every monster/post need to be changed like this:

```
+++ b/_posts/2017-09-10-aarakocra.markdown
@@ -1,22 +1,21 @@
 ---
-layout: post
+layout: single_statblock
 title: "Aarakocra"
 date: 2017-09-10
 tags: [medium, humanoid, cr1/4, monster-manual]
+size: Medium humanoid
+alignment: netrual good
+ac: 12
+hp: 13 (3d8)
+speed: 23 ft., fly 50 ft.
+str: 10
+dex: 14
+con: 10
+int: 11
+wis: 12
+cha: 11
 ---

-**Medium humanoid (aarakocra), neutral good**
-
-**Armor Class** 12
-
-**Hit Points** 13 (3d8)
-
-**Speed** 20 ft., fly 50 ft.
-
-|   STR   |   DEX   |   CON   |   INT   |   WIS   |   CHA   |
-|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
-| 10 (0) | 14 (+2) | 10 (0) | 11 (0) | 12 (+1) | 11 (0) |
```

I want to see if I can manage to make a script to generate the new monsters/posts based on the old ones, so I don't have to manually change all of them.

PS: Some more work needs to be done with the new layout file, as it's not completely correct yet.

**Comment by Kyrremann** [comment]
Another though as I worked with upgrading Jekyll, if we split `size` into `size` and `creature_type`, and move `challenge_rating` out from `tags`, we could do a lot more smoother filtering.

**Comment by chisaipete** [comment]
I'm all for it! I'll love to take a look at your PR. :)

**Comment by Kyrremann** [comment]
I'll create a PR for this on Wednesday, going to focus on #58 first.

**Comment by Kyrremann** [comment]
I'm nearly done with this one. Made a script that transformed all the files to the "proper" format. I'll create a PR tomorrow. As the spacing between actions/skills are a bit too wide.

**Comment by chisaipete** [comment]
How's this going? I finally got all your other changes live (note the favicon) :)

**Comment by Kyrremann** [comment]
> How's this going? I finally got all your other changes live (note the favicon) :)

I was waiting for you to finishing the merge and update with the other PR. I'll run the transformer, and to some random checks, and then I'll push the changes.

**Comment by chisaipete** [comment]
Thanks again, this looks great!
